services:
  db:
    image: postgres:13
    container_name: omero-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${OMERO_DB_USER}
      POSTGRES_PASSWORD: ${OMERO_DB_PASS}
      POSTGRES_DB: ${OMERO_DB_NAME}
    volumes:
      - omero-db:/var/lib/postgresql/data
    networks:
      - omero-net

  server:
    image: openmicroscopy/omero-server
    container_name: omero-server
    restart: always
    env_file: .env
    environment:
      CONFIG_omero_db_host: omero-db
      CONFIG_omero_db_user: ${OMERO_DB_USER}
      CONFIG_omero_db_pass: ${OMERO_DB_PASS}
      CONFIG_omero_db_name: ${OMERO_DB_NAME}
      ROOTPASS: ${OMERO_ROOT_PASS}
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - /omero/data:/OMERO
    depends_on:
      - db
    networks:
      - omero-net

  web:
    image: openmicroscopy/omero-web-standalone
    container_name: omero-web
    restart: always
    env_file: .env
    environment:
      OMEROHOST: omero-server
    ports:
      - "${OMERO_WEB_PORT}:4080"
    depends_on:
      - server
    networks:
      - omero-net

networks:
  omero-net:

volumes:
  omero-db:
